version: '3.7'

services:
  frontend:
    image: registry.gitlab.com/rwf-dev/lstboente/iusr-client/frontend:${COMMIT:-latest}
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    restart: no
    expose:
      - 3000:3000
    env_file:
      - .env
