version: '3.7'

services:
  frontend:
    image: registry.gitlab.com/rwf-dev/lstboente/iusr-client:${COMMIT:-latest}
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    restart: 'no'
    ports:
      - '3000:3000'
